# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d930ce502b39048dd83439c8e8ae23165cb9109fd359945e364b8e91cdbf56116a158134ed10b38aa78fd0d68e4a8fe8c31bb71f08f86a75b4bb61e389331be1

test:
  secret_key_base: cc8d41a1b0734ce76f4350f82e929e2008f988a2025de82544fc1f0325cb32b1cfe80d285480a94571156ed2b2dfa4ec7ab09bf067e5db6d04cfc0f4dcf603fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>